
---@enum ability_data
local ability_data = {
    slash = {
        filename = "60FPS_FA01_01_Slash.png",
        frame_count = 30,
        line_length = 5,
        width = 192,
        height = 192,
        target = "character",
        default_cooldown = 60 * 2,
        default_radius = 5,
        default_damage = 5,
        damage_multiplier = 2,
        radius_multiplier = 1.25,
        cooldown_multiplier = 10,
        upgrade_order = {
            "radius",
            "damage",
            "radius",
            "damage",
            "radius",
            "cooldown",
            "damage",
            "radius",
            "damage",
            "cooldown",
            "radius",
            "damage",
            "damage",
            "cooldown",
            "radius",
            "damage",
            "damage",
            "cooldown",
            "radius",
        }
    },
    thrust = {
        filename = "60FPS_FA01_02_Thrust.png",
        frame_count = 30,
        line_length = 5,
        width = 192,
        height = 192,
        target = "character",
        default_cooldown = 60 * 1.5,
        default_radius = 1.5,
        default_damage = 10,
        damage_multiplier = 1.5,
        radius_multiplier = 2,
        cooldown_multiplier = 0.5,
    },
    punch = {
        filename = "60FPS_FA01_03_Punch.png",
        frame_count = 30,
        line_length = 5,
        width = 192,
        height = 192,
        target = "position",
        default_cooldown = 60 * 1.5,
        default_radius = 1.5,
        default_damage = 10,
        damage_multiplier = 1.5,
        radius_multiplier = 1,
        cooldown_multiplier = 10,
        upgrade_order = {
            "radius",
            "damage",
            "cooldown",
            "radius",
            "damage",
            "cooldown",
            "radius",
            "damage",
            "cooldown",
            "radius",
            "damage",
            "cooldown",
            "radius",
            "damage",
            "cooldown",
        }
    },
    buff = {
        filename = "60FPS_FA01_04_Buff.png",
        frame_count = 60,
        line_length = 5,
        width = 192,
        height = 192,
        target = "position",
        default_cooldown = 60 * 6,
        default_radius = 1.5,
        default_damage = 10,
        damage_multiplier = 1.5,
        radius_multiplier = 2,
        cooldown_multiplier = 0.5,
    },
    shimmer = {
        filename = "60FPS_FA01_06_Shimmer.png",
        frame_count = 60,
        line_length = 5,
        width = 192,
        height = 192,
        target = "character",
        default_cooldown = 60 * 10,
        default_radius = 1.5,
        default_damage = 0,
        damage_multiplier = 1,
        radius_multiplier = 2,
        cooldown_multiplier = 0.5,
    },
    cure = {
        filename = "60FPS_FA01_07_Cure.png",
        frame_count = 70,
        line_length = 5,
        width = 192,
        height = 192,
        target = "character",
        default_cooldown = 60 * 8,
        default_radius = 1,
        default_damage = -0.25,
        damage_multiplier = 1.25,
        radius_multiplier = 2,
        cooldown_multiplier = 30,
        upgrade_order = {
            "damage",
            "damage",
            "cooldown",
            "damage",
            "damage",
            "cooldown",
            "damage",
            "cooldown",
            "damage",
            "cooldown",
        }
    },
    shield = {
        filename = "60FPS_FA01_08_Shield.png",
        frame_count = 60,
        line_length = 5,
        width = 192,
        height = 192,
        target = "character",
        default_cooldown = 60 * 10,
        default_radius = 1.5,
        default_damage = 10,
        damage_multiplier = 1.5,
        radius_multiplier = 2,
        cooldown_multiplier = 0.5,
    },
    barrier = {
        filename = "60FPS_FA01_09_Barrier.png",
        frame_count = 100,
        line_length = 5,
        width = 192,
        height = 192,
        target = "character",
        default_cooldown = 60 * 10,
        default_radius = 1.5,
        default_damage = 10,
        damage_multiplier = 1.5,
        radius_multiplier = 2,
        cooldown_multiplier = 0.5,
    },
    burst = {
        filename = "60FPS_FA01_10_Burst.png",
        frame_count = 100,
        line_length = 5,
        width = 192,
        height = 192,
        target = "position",
        default_cooldown = 60 * 7,
        default_radius = 1,
        default_damage = 25,
        damage_multiplier = 1.5,
        radius_multiplier = 2,
        cooldown_multiplier = 35,
        upgrade_order = {
            "radius",
            "cooldown",
            "damage",
            "radius",
            "cooldown",
            "radius",
            "damage",
            "cooldown",
            "radius",
            "cooldown",
            "damage",
            "radius",
        }
    },
    rocket_launcher = {
        filename = "60FPS_FA01_06_Shimmer.png",
        frame_count = 60,
        line_length = 5,
        width = 192,
        height = 192,
        target = "position",
        default_cooldown = 60 * 0.5,
        default_radius = 15,
        default_damage = 1,
        damage_multiplier = 1.5,
        radius_multiplier = 5,
        cooldown_multiplier = 2,
        upgrade_order = {
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "radius",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "radius",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "radius",
            "cooldown",
            "cooldown",
            "cooldown",
            "radius",
            "radius",
        },
    },
    pavement = {
        filename = "60FPS_FA01_06_Shimmer.png",
        frame_count = 60,
        line_length = 5,
        width = 192,
        height = 192,
        target = "position",
        default_cooldown = 60 * 1/5,
        default_radius = 1,
        default_damage = 1,
        damage_multiplier = 1.5,
        radius_multiplier = 1,
        cooldown_multiplier = 2,
        upgrade_order = {
            "cooldown",
            "cooldown",
            "radius",
            "cooldown",
            "cooldown",
            "radius",
            "cooldown",
            "cooldown",
        },
    },
    beam_chain = {
        filename = "60FPS_FA01_06_Shimmer.png",
        frame_count = 60,
        line_length = 5,
        width = 192,
        height = 192,
        target = "position",
        default_cooldown = 60 * 3.25,
        default_radius = 15,
        default_damage = 33,
        damage_multiplier = 1.5,
        radius_multiplier = 2,
        cooldown_multiplier = 10,
        upgrade_order = {
            "cooldown",
            "cooldown",
            "cooldown",
            "radius",
            "cooldown",
            "cooldown",
            "cooldown",
            "radius",
            "cooldown",
            "cooldown",
            "cooldown",
            "radius",
            "cooldown",
            "cooldown",
            "cooldown",
            "radius",
        },
    },
    discharge_defender = {
        filename = "60FPS_FA01_06_Shimmer.png",
        frame_count = 60,
        line_length = 5,
        width = 192,
        height = 192,
        target = "position",
        default_cooldown = 60 * 6,
        default_radius = 1,
        default_damage = 1,
        damage_multiplier = 1,
        radius_multiplier = 1,
        cooldown_multiplier = 20,
        upgrade_order = {
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
            "cooldown",
        },
    }
}

return {
    ability_data = ability_data,
}